services:
  db:
    container_name: botdata
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: botdb
    ports:
      - 3306:3306
    volumes:
      - botdata:/var/lib/mysql

volumes:
  botdata:
